### ISSUE TITLE
incompatible with tmux 3.3

### ISSUE THREAD

**Issue by kujohn** [laishulu/emacs-tmux-pane#3]
With this plugin enabled via tpm, it causes tmux server to exit:

```
server exited unexpectedly
```

**Comment by laishulu** [comment]
Have you ever used this package with earlier tmux version?

**Comment by kujohn** [comment]
Yes, I was using tmux `3.2a` yesterday and did a update of it today to `3.3`.

**Comment by kujohn** [comment]
Hmm, I'm thinking there would be more issues related to tmux `3.3` than this package. I am getting other bugs/errors.

**Comment by kujohn** [comment]
I fixed the weird output and behavior by fixing `TERM` but this plugin still caused tmux server to exit.

**Comment by kujohn** [comment]
This is no longer the issue.

**Comment by kujohn** [comment]
Actually this problem still exist. I turned this plugin off and tmux launches successfully. When this plugin is on, it'll crash tmux.
