### ISSUE TITLE
tmux-pane seems to be opening a new pane every time the file is required

### ISSUE THREAD

**Issue by dpzmick** [laishulu/emacs-tmux-pane#6]
From here: https://github.com/laishulu/emacs-tmux-pane/blob/master/tmux-pane.el#L108

It looks as if line 119 (copied below)

```
:autoload
(defun tmux-pane-toggle-horizontal()
  "Toggle horizontal pane."
  (interactive)
  ;; have more than one pane
  (if (< 1 (length
            (split-string
             (string-trim
              (tmux-pane--ensure-dir
               (shell-command-to-string "tmux list-panes")) "\n"))))
      (tmux-pane-close)))
(tmux-pane-open-horizontal)
```

is unconditionally opening a horizontal split whenever this file is sourced. For my config, this results in many panes getting opened, at least one new pane every time some other package I'm running spawns some async function call with batch emacs running in the background!

In the previous version (before commit 93f9fcccdc92a70264ca69227a61438a94d42026) the code (https://github.com/laishulu/emacs-tmux-pane/blob/dd34555f2f91b73c3cc7546914a1f53f59608995/tmux-pane.el) seems to have kept the toggle contained in the toggle-horizontal function rather than having the open-horizontal function free-standing:

```
:autoload
(defun toggle-horizontal()
  "Toggle horizontal pane."
  (interactive)
  ;; have more than one pane
  (if (< 1 (length
            (split-string
             (string-trim
              (-ensure-dir 
               (shell-command-to-string "tmux list-panes")) "\n"))))
      (close)
(open-horizontal)))
```

is change this intentional?

**Comment by laishulu** [comment]
Somebody submitted a PR, brought the bug.
Fixing now.

**Comment by dpzmick** [comment]
ha, easy fix. I probably could have handled that myself.

Thank you!
